---
title: "Board Game Analysis"
output:
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: console
---

#Loading in the Data

```{r}
# Hello Dr. Ye. To access this data, you will need to install the following packages and knitr if you want to use the R markdown. Also, be sure to change the read.csv file on line 26. 
library(ggplot2)
library(tidytext)
library(tidyverse)
library(magrittr) 
library(dplyr)
library(forcats)
library(glmnet)
library(Matrix)
```


```{r}
Board_game_raw <- read.csv("C:/Users/Javy/Downloads/BoardGameData.csv")


Rank = Board_game_raw$rank
minPlayer = Board_game_raw$min_players
Maxplayer = Board_game_raw$max_players
BGName = Board_game_raw$names
AvgTime = Board_game_raw$avg_time
MinTime = Board_game_raw$min_time
Maxtime = Board_game_raw$max_time
Year = Board_game_raw$year
AvgRating = Board_game_raw$avg_rating
GeekRating = Board_game_raw$geek_rating
num_votes = Board_game_raw$num_votes
BGAge = Board_game_raw$age
Owned = Board_game_raw$owned
Designer = Board_game_raw$designer
Weight = Board_game_raw$weight
Category = Board_game_raw$Category
Mechanic = Board_game_raw$mechanic
game_id = Board_game_raw$game_id

Board_game_raw = data.frame(BGName, minPlayer, Maxplayer, AvgTime, Maxtime, Year, AvgRating,
                num_votes, BGAge, Category,  Weight, Mechanic, game_id, Rank)

holdout_set <- Board_game_raw%>%
  filter(Board_game_raw$game_id %%5 == 0)

board_games <- Board_game_raw%>%
  filter(Board_game_raw$game_id %%5 != 0)
```

#Exploratory Data Analysis
```{r}

Board_game_raw %>%
  count(Year) %>%
  ggplot(aes(Year,n)) + 
  geom_line() +
  xlim(NA,2020) +
  labs(title = "Games Published")


Board_game_raw %>%
  filter(num_votes>=275)%>% #275 is 1st quant
  ggplot(aes(AvgRating)) +
  geom_histogram() +
  xlab('Average Rating') + labs(title= "Board Game Ratings")
#looks normally distributed around 7 with a right skew


Board_game_raw %>%
  ggplot(aes(sqrt(AvgTime))) + 
  geom_histogram(binwidth = 1.3) 


Board_game_raw %>%
  ggplot(aes(Weight))+
  geom_density() 



Board_game_raw %>% 
  filter(Maxtime > 5, Maxtime<1000)%>%
  ggplot(aes(Maxtime/60))+
  geom_histogram(binwidth = .15)+
  scale_x_log10()
  
plot(density(AvgTime),main = "Density of Average Time")
plot(density(sqrt(AvgTime)),main = "Density of Average Time")

```

#Categorical Variable
```{r}
categorical_vars <- board_games %>% 
  select(BGName, game_id, Mechanic, Category)%>%
  gather(type,value, Mechanic, Category) %>%
  filter(!is.na(value))%>%
  separate_rows(value, sep=",")%>%
  arrange(BGName)




Cat_counts <- categorical_vars%>%
  count(type, value, sort = T)


Cat_counts%>%
  filter(type =='Category')%>%
  head(20)%>%
  mutate(value = fct_reorder(value,n))%>%
  ggplot(aes(value,n))+
  geom_col()+
  coord_flip() + 
  labs(title = 'Most Common Categories')

Cat_counts%>% #Cats and mechs
  group_by(type)%>%
  top_n(20,n)%>%
  ungroup()%>%
  mutate(value = reorder_within(value,n,type), 
         type = reorder(type, n, sum))%>%
  ggplot(aes(value,n, fill = type))+
  geom_col(show.legend = FALSE) +
  facet_wrap(~type, scales = 'free_y')+
  coord_flip() + 
  labs(title = 'Most Common Categories and Mechanics')



```


#Linear Regression 

```{r}


lm(AvgRating ~  Maxplayer + sqrt(AvgTime) + Year + Weight + minPlayer + log10(num_votes) ,board_games) %>% 
  summary()


par(mfrow=c(2,3))
lm1 = board_games %>% ggplot(aes(Maxplayer,AvgRating)) + geom_point() + geom_smooth(method = 'lm')

lm2 = board_games %>% ggplot(aes(sqrt(AvgTime),AvgRating)) + geom_point() + geom_smooth(method = 'lm')

lm3 = board_games %>% ggplot(aes(Year,AvgRating)) + geom_point() + geom_smooth(method = 'lm')

lm4 = board_games %>% ggplot(aes(Weight,AvgRating)) + geom_point() + geom_smooth(method = 'lm')

lm5 = board_games %>% ggplot(aes(minPlayer,AvgRating)) + geom_point() + geom_smooth(method = 'lm')

lm6 = board_games %>% ggplot(aes(log10(num_votes),AvgRating)) + geom_point() + geom_smooth(method = 'lm')

gridExtra::grid.arrange(lm1,lm2,lm3,lm4,lm5,lm6, ncol=3)


```

```{r}

by_categorical <- board_games%>%
  inner_join(categorical_vars, by="game_id")%>%
  select(type, value, AvgRating) %>%
  group_by(type,value)%>%
  summarize(games=n(),
            AvgRating = mean(AvgRating))%>%
  arrange(desc(AvgRating))


summary(lm(data = by_categorical, AvgRating ~ by_categorical$type + by_categorical$value))



Cat_AvgRating_Plot <- board_games%>%
  inner_join(categorical_vars, by="game_id")%>%
  filter(type=='Category')%>%
  mutate(value = fct_lump(value,15),
         value = fct_reorder(value, AvgRating))%>%
  ggplot(aes(value,AvgRating)) + 
  geom_boxplot()+
  coord_flip()+
  labs(title = "Category: Average Rating")+
  xlab('Category') + ylab('Average Rating')

Mech_AvgRating_Plot <- board_games%>%
  inner_join(categorical_vars, by="game_id")%>%
  filter(type=='Mechanic')%>%
  mutate(value = fct_lump(value,15),
         value = fct_reorder(value, AvgRating))%>%
  ggplot(aes(value,AvgRating)) + 
  geom_boxplot()+
  coord_flip()+
  labs(title = "Mechanic: Average Rating")+
  xlab('Mechanic') + ylab('Average Rating')

Cat_AvgRating_Plot  
Mech_AvgRating_Plot 
```

Categorical and Mechanic Variables correlate with a game's average rating. 


```{r}
non_categorical_features <- board_games %>%
  transmute(game_id, 
            BGName, 
            Year,
            log2_max_players = log2(Maxplayer+1),
            Weight,
            log2_max_time = log2(Maxtime))%>%
  gather(feature, value, -game_id, -BGName)

head(non_categorical_features)

features <- categorical_vars%>%
  unite(feature,type, value, sep = ": ")%>%
  add_count(feature)%>%
  filter(n >=20) %>%
  mutate(value = 1)%>%
  bind_rows(non_categorical_features)


```